In [6]:
#Nihar M. Vaidya
import numpy as np

In [7]:
#1. Create a null vector of size 10 but the fifth value which is 1.

a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#2. Create a vector with values ranging from 10 to 49.

b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

mat1 = np.arange(9).reshape(3,3)
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

n = np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4], dtype=int64),)


In [18]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

r = np.random.random((10,10))
print(r)
print("maximum value",np.max(r))
print("minimum value",np.min(r))

[[0.91069911 0.97161945 0.5963763  0.36112207 0.22693782 0.42745009
  0.6661334  0.23247837 0.96188652 0.84764849]
 [0.9177938  0.89581162 0.04199069 0.41614882 0.2562629  0.61643916
  0.26764052 0.92651189 0.11221292 0.89079223]
 [0.92897441 0.41953817 0.95244179 0.76080153 0.09180514 0.85075565
  0.25642028 0.81794056 0.74556098 0.62116791]
 [0.2368306  0.98855653 0.11435165 0.32705764 0.60535341 0.57255135
  0.28157043 0.19896601 0.03922682 0.06509553]
 [0.52965443 0.06093419 0.31987177 0.03047689 0.68764083 0.79116815
  0.60525381 0.8237208  0.74644816 0.67153307]
 [0.93827409 0.0810033  0.8603861  0.22761882 0.38677649 0.36721948
  0.58576073 0.35697544 0.53548364 0.6267675 ]
 [0.35169568 0.03493632 0.3150684  0.75576364 0.69943086 0.73091143
  0.90924652 0.26580757 0.93369185 0.57647599]
 [0.05377758 0.82771598 0.07069761 0.07950148 0.12685168 0.5374115
  0.37110761 0.0929949  0.18465019 0.69372382]
 [0.25698067 0.33852924 0.97992577 0.52511676 0.26697278 0.32716829
  0.32044518 

In [19]:
#6. Create a random vector of size 30 and find the mean value.

c = np.random.random(30)
print(c)
print("mean=",c.mean())

[0.61327542 0.32908068 0.8113229  0.31362914 0.55518067 0.14161019
 0.46862073 0.36041306 0.35163975 0.34676968 0.91191    0.0438989
 0.4588482  0.18536462 0.20772321 0.61697676 0.23519486 0.50693414
 0.04055213 0.41310455 0.25916069 0.10295527 0.09764027 0.1796721
 0.7538411  0.84409621 0.00760357 0.31672762 0.66843615 0.66133239]
mean= 0.39345049985988984
